# Generated by Django 4.2.16 on 2024-11-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staf',
            name='name',
            field=models.CharField(default='Unknown Company', max_length=150),
        ),
    ]
