# Generated by Django 4.2.16 on 2024-11-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0003_alter_staf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staf',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
