# Generated by Django 4.2.16 on 2024-11-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='info'),
        ),
    ]
