# Generated by Django 4.2.16 on 2024-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_info_upload_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='info/'),
        ),
    ]
