# Generated by Django 4.2.16 on 2024-12-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_info_upload_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
