# Generated by Django 4.2.16 on 2024-12-07 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_skills_required_coverletter'),
        ('info', '0006_info_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='applied_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
