# Generated by Django 4.2.16 on 2024-12-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_info_applied_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='applied_job',
        ),
    ]
