# Generated by Django 4.2.17 on 2024-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_remove_info_applied_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
    ]
