# Generated by Django 4.2.17 on 2024-12-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
